FROM node:21-alpine AS build

WORKDIR /usr/src/app

COPY --chown=node:node package*.json ./

RUN npm install

COPY --chown=node:node . .

RUN npm run build

ENV NODE_ENV production

RUN npm ci --only=production && npm cache clean --force

USER node

###################
# PRODUCTION
###################

FROM node:21-alpine As production
RUN apk add openssl

# Copy the bundled code from the build stage to the production image
COPY --chown=node:node --from=build /usr/src/app/node_modules ./node_modules
COPY --chown=node:node --from=build /usr/src/app/dist ./dist

COPY --chown=node:node ./nodeset /nodeset

ENV OPCUA_SERVER_NODESET_PATH=/nodeset
ENV OPCUA_SERVER_HOST=

# Start the server using the production build
CMD [ "node", "dist/src/main.js" ]

EXPOSE 4334